let myDate=new Date()
// console.log(myDate.toString())
// console.log(myDate.toDateString())
// console.log(myDate.toLocaleString())
// console.log(myDate.toJSON())
// console.log(myDate.toLocaleDateString())
// console.log(typeof myDate)

// let myCreatedDate=new Date(2025,9,20,8,3)
// let myCreatedDate=new Date("2023-01-14")
let myCreatedDate=new Date("01-14-2025")

//console.log(myCreatedDate.toLocaleString())
let myTimeStamp=Date.now()
// console.log(myTimeStamp)
// console.log(myCreatedDate.getTime())
let newDate=new Date()
console.log(newDate.getMonth()+1)
console.log(newDate.getDay())